# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NVIDIA-License
#
# Authors: Guojin Chen (work done during internship at NVIDIA), Haoyu Yang
#
# Project: DiffOPC — Differentiable OPC
# Paper:   https://dl.acm.org/doi/10.1145/3676536.3676764
#
# NVIDIA CORPORATION and its affiliates retain all intellectual property and
# proprietary rights in and to this software and related documentation. Any
# use, reproduction, or distribution is subject to the terms of the NVIDIA
# License (see LICENSE in the project root). The work may be used only for
# non-commercial research or evaluation, except by NVIDIA Corporation and
# its affiliates.

Iterations: 80
TargetDensity: 0.225
SigmoidSteepness: 4.0
WeightEPE: 0.5
WeightL2: 2.0
WeightPVBL2: 0.5
WeightPVBand: 0.0
StepSize: 1

TileSizeX: 2048
TileSizeY: 2048
OffsetX: 512
OffsetY: 512
ILTSizeX: 1024
ILTSizeY: 1024
SEG_LENGTH: 60
VISUAL_DEBUG: 0
VERBOSE: 1
Evaluation: 1
